export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PASSWORD_HASHER = Symbol('PASSWORD_HASHER');
export const TOKEN_GENERATOR = Symbol('TOKEN_GENERATOR');

export const LOCATION_REPOSITORY = Symbol('LOCATION_REPOSITORY');
export const GOOGLE_PLACES_PORT = Symbol('GOOGLE_PLACES_PORT');

export const TRUCK_REPOSITORY = Symbol('TRUCK_REPOSITORY');
